apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctaas-dis.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ctaas-dis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.dis.type }}
  ports:
    - name: http-8080
      protocol: TCP
      port: {{ .Values.services.dis.http_port_8080 }}
      targetPort: {{ .Values.services.dis.http_port_8080 }}
    - name: http-9390
      protocol: TCP
      port: {{ .Values.services.dis.http_port_9390 }}
      targetPort: {{ .Values.services.dis.http_port_9390 }}
  selector:
    {{- include "ctaas-dis.selectorLabels" . | nindent 4 }}
